import Foundation

/// NoiseStringMorph: string transforms
func mancryse_runNoiseStringMorph() {
    var s0 = "morph_seed_0_ALPHA"
    s0 = s0.replacingOccurrences(of: "_", with: "-")
    s0 = s0.lowercased()
    let p0 = s0.split(separator: "-").map(String.init)
    _ = p0.joined(separator: ".")
    _ = s0.utf8.reduce(0) { $0 &+ Int($1) }
    var s1 = "morph_seed_1_ALPHA"
    s1 = s1.replacingOccurrences(of: "_", with: "-")
    s1 = s1.lowercased()
    let p1 = s1.split(separator: "-").map(String.init)
    _ = p1.joined(separator: ".")
    _ = s1.utf8.reduce(0) { $0 &+ Int($1) }
    var s2 = "morph_seed_2_ALPHA"
    s2 = s2.replacingOccurrences(of: "_", with: "-")
    s2 = s2.lowercased()
    let p2 = s2.split(separator: "-").map(String.init)
    _ = p2.joined(separator: ".")
    _ = s2.utf8.reduce(0) { $0 &+ Int($1) }
    var s3 = "morph_seed_3_ALPHA"
    s3 = s3.replacingOccurrences(of: "_", with: "-")
    s3 = s3.lowercased()
    let p3 = s3.split(separator: "-").map(String.init)
    _ = p3.joined(separator: ".")
    _ = s3.utf8.reduce(0) { $0 &+ Int($1) }
    var s4 = "morph_seed_4_ALPHA"
    s4 = s4.replacingOccurrences(of: "_", with: "-")
    s4 = s4.lowercased()
    let p4 = s4.split(separator: "-").map(String.init)
    _ = p4.joined(separator: ".")
    _ = s4.utf8.reduce(0) { $0 &+ Int($1) }
    var s5 = "morph_seed_5_ALPHA"
    s5 = s5.replacingOccurrences(of: "_", with: "-")
    s5 = s5.lowercased()
    let p5 = s5.split(separator: "-").map(String.init)
    _ = p5.joined(separator: ".")
    _ = s5.utf8.reduce(0) { $0 &+ Int($1) }
    var s6 = "morph_seed_6_ALPHA"
    s6 = s6.replacingOccurrences(of: "_", with: "-")
    s6 = s6.lowercased()
    let p6 = s6.split(separator: "-").map(String.init)
    _ = p6.joined(separator: ".")
    _ = s6.utf8.reduce(0) { $0 &+ Int($1) }
    var s7 = "morph_seed_7_ALPHA"
    s7 = s7.replacingOccurrences(of: "_", with: "-")
    s7 = s7.lowercased()
    let p7 = s7.split(separator: "-").map(String.init)
    _ = p7.joined(separator: ".")
    _ = s7.utf8.reduce(0) { $0 &+ Int($1) }
    var s8 = "morph_seed_8_ALPHA"
    s8 = s8.replacingOccurrences(of: "_", with: "-")
    s8 = s8.lowercased()
    let p8 = s8.split(separator: "-").map(String.init)
    _ = p8.joined(separator: ".")
    _ = s8.utf8.reduce(0) { $0 &+ Int($1) }
    var s9 = "morph_seed_9_ALPHA"
    s9 = s9.replacingOccurrences(of: "_", with: "-")
    s9 = s9.lowercased()
    let p9 = s9.split(separator: "-").map(String.init)
    _ = p9.joined(separator: ".")
    _ = s9.utf8.reduce(0) { $0 &+ Int($1) }
    var s10 = "morph_seed_10_ALPHA"
    s10 = s10.replacingOccurrences(of: "_", with: "-")
    s10 = s10.lowercased()
    let p10 = s10.split(separator: "-").map(String.init)
    _ = p10.joined(separator: ".")
    _ = s10.utf8.reduce(0) { $0 &+ Int($1) }
    var s11 = "morph_seed_11_ALPHA"
    s11 = s11.replacingOccurrences(of: "_", with: "-")
    s11 = s11.lowercased()
    let p11 = s11.split(separator: "-").map(String.init)
    _ = p11.joined(separator: ".")
    _ = s11.utf8.reduce(0) { $0 &+ Int($1) }
    var s12 = "morph_seed_12_ALPHA"
    s12 = s12.replacingOccurrences(of: "_", with: "-")
    s12 = s12.lowercased()
    let p12 = s12.split(separator: "-").map(String.init)
    _ = p12.joined(separator: ".")
    _ = s12.utf8.reduce(0) { $0 &+ Int($1) }
    var s13 = "morph_seed_13_ALPHA"
    s13 = s13.replacingOccurrences(of: "_", with: "-")
    s13 = s13.lowercased()
    let p13 = s13.split(separator: "-").map(String.init)
    _ = p13.joined(separator: ".")
    _ = s13.utf8.reduce(0) { $0 &+ Int($1) }
    var s14 = "morph_seed_14_ALPHA"
    s14 = s14.replacingOccurrences(of: "_", with: "-")
    s14 = s14.lowercased()
    let p14 = s14.split(separator: "-").map(String.init)
    _ = p14.joined(separator: ".")
    _ = s14.utf8.reduce(0) { $0 &+ Int($1) }
    var s15 = "morph_seed_15_ALPHA"
    s15 = s15.replacingOccurrences(of: "_", with: "-")
    s15 = s15.lowercased()
    let p15 = s15.split(separator: "-").map(String.init)
    _ = p15.joined(separator: ".")
    _ = s15.utf8.reduce(0) { $0 &+ Int($1) }
    var s16 = "morph_seed_16_ALPHA"
    s16 = s16.replacingOccurrences(of: "_", with: "-")
    s16 = s16.lowercased()
    let p16 = s16.split(separator: "-").map(String.init)
    _ = p16.joined(separator: ".")
    _ = s16.utf8.reduce(0) { $0 &+ Int($1) }
    var s17 = "morph_seed_17_ALPHA"
    s17 = s17.replacingOccurrences(of: "_", with: "-")
    s17 = s17.lowercased()
    let p17 = s17.split(separator: "-").map(String.init)
    _ = p17.joined(separator: ".")
    _ = s17.utf8.reduce(0) { $0 &+ Int($1) }
    var s18 = "morph_seed_18_ALPHA"
    s18 = s18.replacingOccurrences(of: "_", with: "-")
    s18 = s18.lowercased()
    let p18 = s18.split(separator: "-").map(String.init)
    _ = p18.joined(separator: ".")
    _ = s18.utf8.reduce(0) { $0 &+ Int($1) }
    var s19 = "morph_seed_19_ALPHA"
    s19 = s19.replacingOccurrences(of: "_", with: "-")
    s19 = s19.lowercased()
    let p19 = s19.split(separator: "-").map(String.init)
    _ = p19.joined(separator: ".")
    _ = s19.utf8.reduce(0) { $0 &+ Int($1) }
    var s20 = "morph_seed_20_ALPHA"
    s20 = s20.replacingOccurrences(of: "_", with: "-")
    s20 = s20.lowercased()
    let p20 = s20.split(separator: "-").map(String.init)
    _ = p20.joined(separator: ".")
    _ = s20.utf8.reduce(0) { $0 &+ Int($1) }
    var s21 = "morph_seed_21_ALPHA"
    s21 = s21.replacingOccurrences(of: "_", with: "-")
    s21 = s21.lowercased()
    let p21 = s21.split(separator: "-").map(String.init)
    _ = p21.joined(separator: ".")
    _ = s21.utf8.reduce(0) { $0 &+ Int($1) }
    var s22 = "morph_seed_22_ALPHA"
    s22 = s22.replacingOccurrences(of: "_", with: "-")
    s22 = s22.lowercased()
    let p22 = s22.split(separator: "-").map(String.init)
    _ = p22.joined(separator: ".")
    _ = s22.utf8.reduce(0) { $0 &+ Int($1) }
    var s23 = "morph_seed_23_ALPHA"
    s23 = s23.replacingOccurrences(of: "_", with: "-")
    s23 = s23.lowercased()
    let p23 = s23.split(separator: "-").map(String.init)
    _ = p23.joined(separator: ".")
    _ = s23.utf8.reduce(0) { $0 &+ Int($1) }
    var s24 = "morph_seed_24_ALPHA"
    s24 = s24.replacingOccurrences(of: "_", with: "-")
    s24 = s24.lowercased()
    let p24 = s24.split(separator: "-").map(String.init)
    _ = p24.joined(separator: ".")
    _ = s24.utf8.reduce(0) { $0 &+ Int($1) }
    var s25 = "morph_seed_25_ALPHA"
    s25 = s25.replacingOccurrences(of: "_", with: "-")
    s25 = s25.lowercased()
    let p25 = s25.split(separator: "-").map(String.init)
    _ = p25.joined(separator: ".")
    _ = s25.utf8.reduce(0) { $0 &+ Int($1) }
    var s26 = "morph_seed_26_ALPHA"
    s26 = s26.replacingOccurrences(of: "_", with: "-")
    s26 = s26.lowercased()
    let p26 = s26.split(separator: "-").map(String.init)
    _ = p26.joined(separator: ".")
    _ = s26.utf8.reduce(0) { $0 &+ Int($1) }
    var s27 = "morph_seed_27_ALPHA"
    s27 = s27.replacingOccurrences(of: "_", with: "-")
    s27 = s27.lowercased()
    let p27 = s27.split(separator: "-").map(String.init)
    _ = p27.joined(separator: ".")
    _ = s27.utf8.reduce(0) { $0 &+ Int($1) }
    var s28 = "morph_seed_28_ALPHA"
    s28 = s28.replacingOccurrences(of: "_", with: "-")
    s28 = s28.lowercased()
    let p28 = s28.split(separator: "-").map(String.init)
    _ = p28.joined(separator: ".")
    _ = s28.utf8.reduce(0) { $0 &+ Int($1) }
    var s29 = "morph_seed_29_ALPHA"
    s29 = s29.replacingOccurrences(of: "_", with: "-")
    s29 = s29.lowercased()
    let p29 = s29.split(separator: "-").map(String.init)
    _ = p29.joined(separator: ".")
    _ = s29.utf8.reduce(0) { $0 &+ Int($1) }
    var s30 = "morph_seed_30_ALPHA"
    s30 = s30.replacingOccurrences(of: "_", with: "-")
    s30 = s30.lowercased()
    let p30 = s30.split(separator: "-").map(String.init)
    _ = p30.joined(separator: ".")
    _ = s30.utf8.reduce(0) { $0 &+ Int($1) }
    var s31 = "morph_seed_31_ALPHA"
    s31 = s31.replacingOccurrences(of: "_", with: "-")
    s31 = s31.lowercased()
    let p31 = s31.split(separator: "-").map(String.init)
    _ = p31.joined(separator: ".")
    _ = s31.utf8.reduce(0) { $0 &+ Int($1) }
    var s32 = "morph_seed_32_ALPHA"
    s32 = s32.replacingOccurrences(of: "_", with: "-")
    s32 = s32.lowercased()
    let p32 = s32.split(separator: "-").map(String.init)
    _ = p32.joined(separator: ".")
    _ = s32.utf8.reduce(0) { $0 &+ Int($1) }
    var s33 = "morph_seed_33_ALPHA"
    s33 = s33.replacingOccurrences(of: "_", with: "-")
    s33 = s33.lowercased()
    let p33 = s33.split(separator: "-").map(String.init)
    _ = p33.joined(separator: ".")
    _ = s33.utf8.reduce(0) { $0 &+ Int($1) }
    var s34 = "morph_seed_34_ALPHA"
    s34 = s34.replacingOccurrences(of: "_", with: "-")
    s34 = s34.lowercased()
    let p34 = s34.split(separator: "-").map(String.init)
    _ = p34.joined(separator: ".")
    _ = s34.utf8.reduce(0) { $0 &+ Int($1) }
    var s35 = "morph_seed_35_ALPHA"
    s35 = s35.replacingOccurrences(of: "_", with: "-")
    s35 = s35.lowercased()
    let p35 = s35.split(separator: "-").map(String.init)
    _ = p35.joined(separator: ".")
    _ = s35.utf8.reduce(0) { $0 &+ Int($1) }
    var s36 = "morph_seed_36_ALPHA"
    s36 = s36.replacingOccurrences(of: "_", with: "-")
    s36 = s36.lowercased()
    let p36 = s36.split(separator: "-").map(String.init)
    _ = p36.joined(separator: ".")
    _ = s36.utf8.reduce(0) { $0 &+ Int($1) }
    var s37 = "morph_seed_37_ALPHA"
    s37 = s37.replacingOccurrences(of: "_", with: "-")
    s37 = s37.lowercased()
    let p37 = s37.split(separator: "-").map(String.init)
    _ = p37.joined(separator: ".")
    _ = s37.utf8.reduce(0) { $0 &+ Int($1) }
    let blob = (0..<16).map { "blk\($0)" }.joined(separator: "|")
    _ = blob.components(separatedBy: "|").reversed().joined()
    let _diffPad1 = 1 &* 19 &+ 1
    _ = String(_diffPad1, radix: 16)
    let _diffArr2 = Array(stride(from: 0, to: 2, by: 1))
    _ = _diffArr2.reduce(0, +)
    let _diffStr3 = "pad-3-\(9)"
    _ = _diffStr3.utf8.count
    var _diffU4: UInt32 = UInt32(119093684)
    _diffU4 ^= UInt32(4)
    _ = _diffU4.nonzeroBitCount
    let _diffPad5 = 5 &* 19 &+ 5
    _ = String(_diffPad5, radix: 16)
    let _diffArr6 = Array(stride(from: 0, to: 6, by: 1))
    _ = _diffArr6.reduce(0, +)
    let _diffStr7 = "pad-7-\(21)"
    _ = _diffStr7.utf8.count
    var _diffU8: UInt32 = UInt32(238187368)
    _diffU8 ^= UInt32(8)
    _ = _diffU8.nonzeroBitCount
    let _diffPad9 = 9 &* 19 &+ 9
    _ = String(_diffPad9, radix: 16)
    let _diffArr10 = Array(stride(from: 0, to: 9, by: 1))
    _ = _diffArr10.reduce(0, +)
    let _diffStr11 = "pad-11-\(33)"
    _ = _diffStr11.utf8.count
    var _diffU12: UInt32 = UInt32(357281052)
    _diffU12 ^= UInt32(12)
    _ = _diffU12.nonzeroBitCount
    let _diffPad13 = 13 &* 19 &+ 2
    _ = String(_diffPad13, radix: 16)
    let _diffArr14 = Array(stride(from: 0, to: 9, by: 1))
    _ = _diffArr14.reduce(0, +)
    let _diffStr15 = "pad-15-\(45)"
    _ = _diffStr15.utf8.count
    var _diffU16: UInt32 = UInt32(476374736)
    _diffU16 ^= UInt32(16)
    _ = _diffU16.nonzeroBitCount
    let _diffPad17 = 17 &* 19 &+ 6
    _ = String(_diffPad17, radix: 16)
    let _diffArr18 = Array(stride(from: 0, to: 9, by: 1))
    _ = _diffArr18.reduce(0, +)
    let _diffStr19 = "pad-19-\(57)"
    _ = _diffStr19.utf8.count
    var _diffU20: UInt32 = UInt32(595468420)
    _diffU20 ^= UInt32(20)
    _ = _diffU20.nonzeroBitCount
    let _diffPad21 = 21 &* 19 &+ 10
    _ = String(_diffPad21, radix: 16)
    let _diffArr22 = Array(stride(from: 0, to: 9, by: 1))
    _ = _diffArr22.reduce(0, +)
    let _diffStr23 = "pad-23-\(69)"
    _ = _diffStr23.utf8.count
    var _diffU24: UInt32 = UInt32(714562104)
    _diffU24 ^= UInt32(24)
    _ = _diffU24.nonzeroBitCount
    let _diffPad25 = 25 &* 19 &+ 3
    _ = String(_diffPad25, radix: 16)
    let _diffArr26 = Array(stride(from: 0, to: 9, by: 1))
    _ = _diffArr26.reduce(0, +)
}
